### ISSUE TITLE
lodash help

### ISSUE THREAD

**Issue by hydrabolt** [devsnek/ldaas#1]
so i used lodash and now i have been told i need to cleanse my soul is this true??

**Comment by GusCaplan** [comment]
i'm afraid so, you can see [here](https://www.google.com/search?q=how+to+exorcise+a+demon) for details on how to. Please close this issue when you are successful.

**Comment by hydrabolt** [comment]
![lodashiscancer](https://cloud.githubusercontent.com/assets/10330923/22856404/a7c1f36e-f088-11e6-9c4d-58c8695608de.png)

Your link took me to a Google search which suggested both performing _and_ exorcising - as a lodash user, I do not have the capabilities to multitask. Is it possible at all there is a lodash implementation that combines the two, or even better just refers me to native code that does the exact same thing?

Thanks

**Comment by GusCaplan** [comment]
You are actually in luck! Node exposes a native implementation via `process.binding('exorcism')`

**Comment by hydrabolt** [comment]
Yes but as a lodash user, I am incapable of using native methods. Is there a lodash implementation of this?
